name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username janfrederickk --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/janfrederickk/ferienprogrammwaiting:latest
          docker push ghcr.io/janfrederickk/ferienprogrammwaiting:latest